# Generated by Django 5.2 on 2025-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('std', models.IntegerField()),
                ('division', models.CharField(max_length=1)),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
